apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  annotations: 
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi