apiVersion: extensions/v1beta1
kind: Ingress 
metadata: 
  name: ingress-service
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kuebrnetes.io/ssl-redirec: 'true'
spec:
  tls:
    - hosts:
        - cyberk.net
        - www.cyberk.net
      secretName: cyberk-net
  rules:
    - host: cyberk.net
      http: 
        paths:
          - path: /
            backend: 
              serviceName: client-cluster-ip-service
              servicePort: 3000
          - path: /api/
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000
    - host: www.cyberk.net
      http: 
        paths:
          - path: /
            backend: 
              serviceName: client-cluster-ip-service
              servicePort: 3000
          - path: /api/
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000